import type { TwitchData, SavedSearch } from "./types";

// Hardcoded examples for the UI demonstration
// export const mockTwitchData: TwitchData[] = [
//   {
//     id: "1",
//     username: "pokimane",
//     channelUrl: "https://twitch.tv/pokimane",
//     followers: 9200000,
//     viewers: 12500,
//     language: "English",
//     category: "Just Chatting",
//     discord: "https://discord.gg/pokimane",
//     youtube: "https://youtube.com/pokimane",
//     twitter: "https://twitter.com/pokimane",
//     facebook: "https://facebook.com/pokimane",
//     instagram: "https://instagram.com/pokimane",
//     email: "business@pokimane.com",
//   },
//   {
//     id: "2",
//     username: "xQc",
//     channelUrl: "https://twitch.tv/xqc",
//     followers: 11500000,
//     viewers: 35000,
//     language: "English",
//     category: "Just Chatting",
//     discord: "https://discord.gg/xqc",
//     youtube: "https://youtube.com/xqc",
//     twitter: "https://twitter.com/xqc",
//     facebook: "",
//     instagram: "https://instagram.com/xqc",
//     email: "business@xqc.gg",
//   },
//   {
//     id: "3",
//     username: "ibai",
//     channelUrl: "https://twitch.tv/ibai",
//     followers: 8500000,
//     viewers: 28000,
//     language: "Spanish",
//     category: "Just Chatting",
//     discord: "https://discord.gg/ibai",
//     youtube: "https://youtube.com/ibai",
//     twitter: "https://twitter.com/ibai",
//     facebook: "https://facebook.com/ibai",
//     instagram: "https://instagram.com/ibai",
//     email: "contacto@ibai.com",
//   },
//   {
//     id: "4",
//     username: "auronplay",
//     channelUrl: "https://twitch.tv/auronplay",
//     followers: 10200000,
//     viewers: 32000,
//     language: "Spanish",
//     category: "Just Chatting",
//     discord: "https://discord.gg/auronplay",
//     youtube: "https://youtube.com/auronplay",
//     twitter: "https://twitter.com/auronplay",
//     facebook: "https://facebook.com/auronplay",
//     instagram: "https://instagram.com/auronplay",
//     email: "business@auronplay.com",
//   },
//   {
//     id: "5",
//     username: "ninja",
//     channelUrl: "https://twitch.tv/ninja",
//     followers: 18500000,
//     viewers: 15000,
//     language: "English",
//     category: "Fortnite",
//     discord: "https://discord.gg/ninja",
//     youtube: "https://youtube.com/ninja",
//     twitter: "https://twitter.com/ninja",
//     facebook: "https://facebook.com/ninja",
//     instagram: "https://instagram.com/ninja",
//     email: "business@ninja.com",
//   },
// ];

// Hardcoded examples for saved searches
export const mockSavedSearches: SavedSearch[] = [
  {
    id: "saved1",
    name: "English Fortnite Streamers",
    filters: {
      searchTerm: "",
      language: "english",
      category: "fortnite",
      minFollowers: 100000,
      maxFollowers: 10000000,
      minViewers: 1000,
      maxViewers: 100000,
    },
  },
  {
    id: "saved2",
    name: "Spanish Just Chatting",
    filters: {
      searchTerm: "",
      language: "spanish",
      category: "just-chatting",
      minFollowers: 500000,
      maxFollowers: 10000000,
      minViewers: 5000,
      maxViewers: 100000,
    },
  },
];

// Hardcoded examples for search history
export const mockSearchHistory = [
  {
    id: "history1",
    date: new Date("2023-04-15T10:30:00"),
    query: "ninja",
    results: 1,
  },
  {
    id: "history2",
    date: new Date("2023-04-14T15:45:00"),
    query: "All streamers",
    results: 15,
  },
];
