import type { TwitchData } from "./types"

// Mock data for demonstration
export const mockTwitchData: TwitchData[] = [
  {
    id: "1",
    username: "pokimane",
    channelUrl: "https://twitch.tv/pokimane",
    followers: 9200000,
    viewers: 12500,
    language: "English",
    category: "Just Chatting",
    discord: "https://discord.gg/pokimane",
    youtube: "https://youtube.com/pokimane",
    twitter: "https://twitter.com/pokimane",
    facebook: "https://facebook.com/pokimane",
    instagram: "https://instagram.com/pokimane",
    email: "business@pokimane.com",
  },
  {
    id: "2",
    username: "xQc",
    channelUrl: "https://twitch.tv/xqc",
    followers: 11500000,
    viewers: 35000,
    language: "English",
    category: "Just Chatting",
    discord: "https://discord.gg/xqc",
    youtube: "https://youtube.com/xqc",
    twitter: "https://twitter.com/xqc",
    facebook: "",
    instagram: "https://instagram.com/xqc",
    email: "business@xqc.gg",
  },
  {
    id: "3",
    username: "ibai",
    channelUrl: "https://twitch.tv/ibai",
    followers: 8500000,
    viewers: 28000,
    language: "Spanish",
    category: "Just Chatting",
    discord: "https://discord.gg/ibai",
    youtube: "https://youtube.com/ibai",
    twitter: "https://twitter.com/ibai",
    facebook: "https://facebook.com/ibai",
    instagram: "https://instagram.com/ibai",
    email: "contacto@ibai.com",
  },
  {
    id: "4",
    username: "auronplay",
    channelUrl: "https://twitch.tv/auronplay",
    followers: 10200000,
    viewers: 32000,
    language: "Spanish",
    category: "Just Chatting",
    discord: "https://discord.gg/auronplay",
    youtube: "https://youtube.com/auronplay",
    twitter: "https://twitter.com/auronplay",
    facebook: "https://facebook.com/auronplay",
    instagram: "https://instagram.com/auronplay",
    email: "business@auronplay.com",
  },
  {
    id: "5",
    username: "ninja",
    channelUrl: "https://twitch.tv/ninja",
    followers: 18500000,
    viewers: 15000,
    language: "English",
    category: "Fortnite",
    discord: "https://discord.gg/ninja",
    youtube: "https://youtube.com/ninja",
    twitter: "https://twitter.com/ninja",
    facebook: "https://facebook.com/ninja",
    instagram: "https://instagram.com/ninja",
    email: "business@ninja.com",
  },
  {
    id: "6",
    username: "shroud",
    channelUrl: "https://twitch.tv/shroud",
    followers: 10100000,
    viewers: 18000,
    language: "English",
    category: "Valorant",
    discord: "https://discord.gg/shroud",
    youtube: "https://youtube.com/shroud",
    twitter: "https://twitter.com/shroud",
    facebook: "https://facebook.com/shroud",
    instagram: "https://instagram.com/shroud",
    email: "business@shroud.gg",
  },
  {
    id: "7",
    username: "tfue",
    channelUrl: "https://twitch.tv/tfue",
    followers: 11000000,
    viewers: 14000,
    language: "English",
    category: "Fortnite",
    discord: "https://discord.gg/tfue",
    youtube: "https://youtube.com/tfue",
    twitter: "https://twitter.com/tfue",
    facebook: "https://facebook.com/tfue",
    instagram: "https://instagram.com/tfue",
    email: "business@tfue.com",
  },
  {
    id: "8",
    username: "rubius",
    channelUrl: "https://twitch.tv/rubius",
    followers: 12500000,
    viewers: 25000,
    language: "Spanish",
    category: "Just Chatting",
    discord: "https://discord.gg/rubius",
    youtube: "https://youtube.com/rubius",
    twitter: "https://twitter.com/rubius",
    facebook: "https://facebook.com/rubius",
    instagram: "https://instagram.com/rubius",
    email: "contacto@rubius.com",
  },
  {
    id: "9",
    username: "asmongold",
    channelUrl: "https://twitch.tv/asmongold",
    followers: 3200000,
    viewers: 60000,
    language: "English",
    category: "World of Warcraft",
    discord: "https://discord.gg/asmongold",
    youtube: "https://youtube.com/asmongold",
    twitter: "https://twitter.com/asmongold",
    facebook: "",
    instagram: "",
    email: "business@asmongold.com",
  },
  {
    id: "10",
    username: "amouranth",
    channelUrl: "https://twitch.tv/amouranth",
    followers: 6300000,
    viewers: 22000,
    language: "English",
    category: "Just Chatting",
    discord: "https://discord.gg/amouranth",
    youtube: "https://youtube.com/amouranth",
    twitter: "https://twitter.com/amouranth",
    facebook: "https://facebook.com/amouranth",
    instagram: "https://instagram.com/amouranth",
    email: "business@amouranth.com",
  },
  {
    id: "11",
    username: "sodapoppin",
    channelUrl: "https://twitch.tv/sodapoppin",
    followers: 3500000,
    viewers: 25000,
    language: "English",
    category: "Just Chatting",
    discord: "https://discord.gg/sodapoppin",
    youtube: "https://youtube.com/sodapoppin",
    twitter: "https://twitter.com/sodapoppin",
    facebook: "",
    instagram: "https://instagram.com/sodapoppin",
    email: "business@sodapoppin.com",
  },
  {
    id: "12",
    username: "summit1g",
    channelUrl: "https://twitch.tv/summit1g",
    followers: 6100000,
    viewers: 30000,
    language: "English",
    category: "Grand Theft Auto V",
    discord: "https://discord.gg/summit1g",
    youtube: "https://youtube.com/summit1g",
    twitter: "https://twitter.com/summit1g",
    facebook: "https://facebook.com/summit1g",
    instagram: "https://instagram.com/summit1g",
    email: "business@summit1g.gg",
  },
  {
    id: "13",
    username: "elrubius",
    channelUrl: "https://twitch.tv/elrubius",
    followers: 11800000,
    viewers: 40000,
    language: "Spanish",
    category: "Just Chatting",
    discord: "https://discord.gg/elrubius",
    youtube: "https://youtube.com/elrubius",
    twitter: "https://twitter.com/elrubius",
    facebook: "https://facebook.com/elrubius",
    instagram: "https://instagram.com/elrubius",
    email: "contacto@elrubius.com",
  },
  {
    id: "14",
    username: "nickmercs",
    channelUrl: "https://twitch.tv/nickmercs",
    followers: 6700000,
    viewers: 35000,
    language: "English",
    category: "Call of Duty: Warzone",
    discord: "https://discord.gg/nickmercs",
    youtube: "https://youtube.com/nickmercs",
    twitter: "https://twitter.com/nickmercs",
    facebook: "https://facebook.com/nickmercs",
    instagram: "https://instagram.com/nickmercs",
    email: "business@nickmercs.com",
  },
  {
    id: "15",
    username: "timthetatman",
    channelUrl: "https://twitch.tv/timthetatman",
    followers: 7200000,
    viewers: 30000,
    language: "English",
    category: "Call of Duty: Warzone",
    discord: "https://discord.gg/timthetatman",
    youtube: "https://youtube.com/timthetatman",
    twitter: "https://twitter.com/timthetatman",
    facebook: "https://facebook.com/timthetatman",
    instagram: "https://instagram.com/timthetatman",
    email: "business@timthetatman.com",
  },
]
