import type { YouTubeData } from "./types"

export const mockYouTubeData: YouTubeData[] = [
  {
    id: "yt1",
    channelName: "TechReviewPro",
    channelUrl: "https://youtube.com/techreviewpro",
    subscribers: 1250000,
    averageViews: 350000,
    language: "english",
    category: "tech",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/techreviewpro",
    twitter: "https://twitter.com/techreviewpro",
    facebook: "https://facebook.com/techreviewpro",
    instagram: "https://instagram.com/techreviewpro",
    email: "contact@techreviewpro.com",
  },
  {
    id: "yt2",
    channelName: "GamingWithJosh",
    channelUrl: "https://youtube.com/gamingwithjosh",
    subscribers: 3500000,
    averageViews: 750000,
    language: "english",
    category: "gaming",
    uploadFrequency: "daily",
    discord: "https://discord.gg/gamingwithjosh",
    twitter: "https://twitter.com/gamingwithjosh",
    facebook: "",
    instagram: "https://instagram.com/gamingwithjosh",
    email: "josh@gamingwithjosh.com",
  },
  {
    id: "yt3",
    channelName: "FitnessFanatic",
    channelUrl: "https://youtube.com/fitnessfanatic",
    subscribers: 850000,
    averageViews: 200000,
    language: "english",
    category: "fitness",
    uploadFrequency: "bi-weekly",
    discord: "",
    twitter: "https://twitter.com/fitnessfanatic",
    facebook: "https://facebook.com/fitnessfanatic",
    instagram: "https://instagram.com/fitnessfanatic",
    email: "info@fitnessfanatic.com",
  },
  {
    id: "yt4",
    channelName: "CookingMaster",
    channelUrl: "https://youtube.com/cookingmaster",
    subscribers: 1800000,
    averageViews: 450000,
    language: "spanish",
    category: "cooking",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/cookingmaster",
    twitter: "https://twitter.com/cookingmaster",
    facebook: "https://facebook.com/cookingmaster",
    instagram: "https://instagram.com/cookingmaster",
    email: "chef@cookingmaster.com",
  },
  {
    id: "yt5",
    channelName: "ScienceExplained",
    channelUrl: "https://youtube.com/scienceexplained",
    subscribers: 2200000,
    averageViews: 500000,
    language: "english",
    category: "education",
    uploadFrequency: "bi-weekly",
    discord: "https://discord.gg/scienceexplained",
    twitter: "https://twitter.com/scienceexplained",
    facebook: "https://facebook.com/scienceexplained",
    instagram: "",
    email: "contact@scienceexplained.com",
  },
  {
    id: "yt6",
    channelName: "TravelWithMaria",
    channelUrl: "https://youtube.com/travelwithmaria",
    subscribers: 950000,
    averageViews: 300000,
    language: "english",
    category: "travel",
    uploadFrequency: "monthly",
    discord: "",
    twitter: "https://twitter.com/travelwithmaria",
    facebook: "https://facebook.com/travelwithmaria",
    instagram: "https://instagram.com/travelwithmaria",
    email: "maria@travelwithmaria.com",
  },
  {
    id: "yt7",
    channelName: "BeautyGuru",
    channelUrl: "https://youtube.com/beautyguru",
    subscribers: 4200000,
    averageViews: 900000,
    language: "english",
    category: "beauty",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/beautyguru",
    twitter: "https://twitter.com/beautyguru",
    facebook: "https://facebook.com/beautyguru",
    instagram: "https://instagram.com/beautyguru",
    email: "collab@beautyguru.com",
  },
  {
    id: "yt8",
    channelName: "BusinessInsider",
    channelUrl: "https://youtube.com/businessinsider",
    subscribers: 1500000,
    averageViews: 400000,
    language: "english",
    category: "business",
    uploadFrequency: "daily",
    discord: "",
    twitter: "https://twitter.com/businessinsider",
    facebook: "https://facebook.com/businessinsider",
    instagram: "https://instagram.com/businessinsider",
    email: "info@businessinsider.com",
  },
  {
    id: "yt9",
    channelName: "MusicProduction",
    channelUrl: "https://youtube.com/musicproduction",
    subscribers: 750000,
    averageViews: 180000,
    language: "english",
    category: "music",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/musicproduction",
    twitter: "https://twitter.com/musicproduction",
    facebook: "",
    instagram: "https://instagram.com/musicproduction",
    email: "studio@musicproduction.com",
  },
  {
    id: "yt10",
    channelName: "GamingNews",
    channelUrl: "https://youtube.com/gamingnews",
    subscribers: 2800000,
    averageViews: 650000,
    language: "english",
    category: "gaming",
    uploadFrequency: "daily",
    discord: "https://discord.gg/gamingnews",
    twitter: "https://twitter.com/gamingnews",
    facebook: "https://facebook.com/gamingnews",
    instagram: "https://instagram.com/gamingnews",
    email: "news@gamingnews.com",
  },
  {
    id: "yt11",
    channelName: "DIYProjects",
    channelUrl: "https://youtube.com/diyprojects",
    subscribers: 1100000,
    averageViews: 320000,
    language: "english",
    category: "entertainment",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/diyprojects",
    twitter: "https://twitter.com/diyprojects",
    facebook: "https://facebook.com/diyprojects",
    instagram: "https://instagram.com/diyprojects",
    email: "projects@diyprojects.com",
  },
  {
    id: "yt12",
    channelName: "TechTutorials",
    channelUrl: "https://youtube.com/techtutorials",
    subscribers: 980000,
    averageViews: 250000,
    language: "english",
    category: "tech",
    uploadFrequency: "bi-weekly",
    discord: "https://discord.gg/techtutorials",
    twitter: "https://twitter.com/techtutorials",
    facebook: "",
    instagram: "https://instagram.com/techtutorials",
    email: "help@techtutorials.com",
  },
  {
    id: "yt13",
    channelName: "LanguageLearning",
    channelUrl: "https://youtube.com/languagelearning",
    subscribers: 1300000,
    averageViews: 380000,
    language: "english",
    category: "education",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/languagelearning",
    twitter: "https://twitter.com/languagelearning",
    facebook: "https://facebook.com/languagelearning",
    instagram: "https://instagram.com/languagelearning",
    email: "learn@languagelearning.com",
  },
  {
    id: "yt14",
    channelName: "MovieReviews",
    channelUrl: "https://youtube.com/moviereviews",
    subscribers: 2100000,
    averageViews: 580000,
    language: "english",
    category: "entertainment",
    uploadFrequency: "weekly",
    discord: "https://discord.gg/moviereviews",
    twitter: "https://twitter.com/moviereviews",
    facebook: "https://facebook.com/moviereviews",
    instagram: "https://instagram.com/moviereviews",
    email: "reviews@moviereviews.com",
  },
  {
    id: "yt15",
    channelName: "FinanceTips",
    channelUrl: "https://youtube.com/financetips",
    subscribers: 920000,
    averageViews: 270000,
    language: "english",
    category: "business",
    uploadFrequency: "bi-weekly",
    discord: "",
    twitter: "https://twitter.com/financetips",
    facebook: "https://facebook.com/financetips",
    instagram: "https://instagram.com/financetips",
    email: "advice@financetips.com",
  },
]
